apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ template "name" . }}"
  namespace: {{ .Values.service.namespace }}
  version: "{{ .Values.service.version }}"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  {{ if .Values.global.rollingupdate }}
  progressDeadlineSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  {{ end }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "{{ template "name" . }}"
      version: "{{ .Values.service.version }}"
  template:
    metadata:
      labels:
        app: "{{ template "name" . }}"
        version: "{{ .Values.service.version }}"
      annotations:
        "sidecar.istio.io/inject": "true"
    spec:
      {{ if .Values.global.healthcheck }}
      terminationGracePeriodSeconds: 60
      {{ end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.container.port }}
          name: http
        {{ if .Values.global.healthcheck }}
        lifecycle:
          preStop:
            exec:
              command:
              - sleep
              - "10"
        livenessProbe:
          exec:
            command:
            - wget
            - --tries=1
            - --timeout=4
            - --spider
            - http://localhost:{{ .Values.service.port }}/status/healthz
          timeoutSeconds: 5
          initialDelaySeconds: 5
          periodSeconds: 3
        readinessProbe:
          exec:
            command:
            - wget
            - --tries=1
            - --timeout=4
            - --spider
            - http://localhost:{{ .Values.service.port }}/status/readyz
          timeoutSeconds: 5
          initialDelaySeconds: 5
          periodSeconds: 3
        {{ end }}
        env:
        - name: ELASTIC_APM_SERVICE_NAME
          value: {{ .Values.service.name }}
        - name: ELASTIC_APM_SERVICE_VERSION
          value: {{ .Values.service.version }}
        - name: ELASTIC_APM_ENVIRONMENT
          value: {{ .Values.service.namespace }}
        - name: ELASTIC_APM_TRANSACTION_SAMPLE_RATE
          value: "1.0"
        - name: ELASTIC_APM_SERVER_URLS
          value: {{ .Values.apm.server }}
        - name: ELASTIC_APM_SECRET_TOKEN
          value: {{ .Values.apm.token }}
        - name: ELASTIC_APM_SPAN_FRAMES_MIN_DURATION
          value: "-1ms"
        - name: JAEGER_SERVICE_NAME
          value: "{{ .Values.service.name }}.{{ .Values.service.namespace }}"
        - name: JAEGER_SAMPLER_TYPE
          value: const
        - name: JAEGER_SAMPLER_PARAM
          value: "1"
        - name: JAEGER_SREPORTER_LOG_SPANS
          value: "true"
        - name: JAEGER_PROPAGATION # Jaeger / B3
          value: "B3"
        - name: ASPNETCORE_REDIS
          value: redis:6379
        - name: ASPNETCORE_BACKEND_VERSION
          value: {{ .Values.service.version }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
