{
 "title": "Cluster Monitoring",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "label_values(kubernetes_io_hostname)"
   },
   { "name": "Namespace", "query": "label_values(namespace)" },
   {
    "name": "Container",
    "query": "label_values(kube_pod_container_info{namespace=~\"^$Namespace$\"}, container)"
   },
   {
    "name": "SourceWorkload",
    "label": "Source Workload",
    "query": "label_values(istio_requests_total{source_workload_namespace=~\"^$SourceWorkloadNamespace$\"}, source_workload)"
   },
   {
    "name": "SourceWorkloadNamespace",
    "label": "Source Workload Namespace",
    "query": "label_values(istio_requests_total, source_workload_namespace)"
   },
   {
    "name": "DestinationWorkload",
    "label": "Destination Workload",
    "query": "label_values(istio_requests_total{destination_workload_namespace=~\"^$DestinationWorkloadNamespace$\"}, destination_workload)"
   },
   {
    "name": "DestinationWorkloadNamespace",
    "label": "Destination Workload Namespace",
    "query": "label_values(istio_requests_total, destination_workload_namespace)"
   }
  ]
 },
 "panels": [
  { "title": "Ingress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ingress Success Rate (non-4|5xx responses)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{destination_workload=~\"$DestinationWorkload\",destination_workload_namespace=~\"$DestinationWorkloadNamespace\",source_workload=~\"$SourceWorkload\",source_workload_namespace=~\"$SourceWorkloadNamespace\",response_code!~\"[4-5].*\"}[2m]))\n/ sum(rate(istio_requests_total{destination_workload=~\"$DestinationWorkload\",destination_workload_namespace=~\"$DestinationWorkloadNamespace\",source_workload=~\"$SourceWorkload\",source_workload_namespace=~\"$SourceWorkloadNamespace\"}[2m]))",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "Ingress Percentile Response Times and Transfer Rates",
   "type": "table",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(istio_request_duration_seconds_bucket{destination_workload=~\"$DestinationWorkload\",destination_workload_namespace=~\"$DestinationWorkloadNamespace\",source_workload=~\"$SourceWorkload\",source_workload_namespace=~\"$SourceWorkloadNamespace\"}[2m])) by (le,source_app, destination_app))"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(istio_request_duration_seconds_bucket{destination_workload=~\"$DestinationWorkload\",destination_workload_namespace=~\"$DestinationWorkloadNamespace\",source_workload=~\"$SourceWorkload\",source_workload_namespace=~\"$SourceWorkloadNamespace\"}[2m])) by (le, source_app, destination_app))"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(istio_request_duration_seconds_bucket{destination_workload=~\"$DestinationWorkload\",destination_workload_namespace=~\"$DestinationWorkloadNamespace\",source_workload=~\"$SourceWorkload\",source_workload_namespace=~\"$SourceWorkloadNamespace\"}[2m])) by (le,source_app, destination_app))"
    },
    {
     "expr": "sum(irate(istio_request_bytes_sum{destination_workload=~\"$DestinationWorkload\",destination_workload_namespace=~\"$DestinationWorkloadNamespace\",source_workload=~\"$SourceWorkload\",source_workload_namespace=~\"$SourceWorkloadNamespace\"}[2m])) by (source_app, destination_app)",
     "legendFormat": "{{ ingress }}"
    },
    {
     "expr": "sum(irate(istio_request_bytes_sum{destination_workload=~\"$DestinationWorkload\",destination_workload_namespace=~\"$DestinationWorkloadNamespace\",source_workload=~\"$SourceWorkload\",source_workload_namespace=~\"$SourceWorkloadNamespace\"}[2m])) by (source_app, destination_app)",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "Ingress Request Volume",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(istio_requests_total{destination_workload=~\"$DestinationWorkload\",destination_workload_namespace=~\"$DestinationWorkloadNamespace\",source_workload=~\"$SourceWorkload\",source_workload_namespace=~\"$SourceWorkloadNamespace\"}[2m])), 0.001)",
     "legendFormat": "{{ volume }}"
    }
   ]
  },
  {
   "title": "Network I/O pressure",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (irate (istio_request_bytes_sum{destination_workload=~\"$DestinationWorkload\",destination_workload_namespace=~\"$DestinationWorkloadNamespace\",source_workload=~\"$SourceWorkload\",source_workload_namespace=~\"$SourceWorkloadNamespace\"}[2m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (irate (istio_response_bytes_sum{destination_workload=~\"^$DestinationWorkload$\",destination_workload_namespace=~\"^$DestinationWorkloadNamespace$\",source_workload=~\"^$SourceWorkload$\",source_workload_namespace=~\"^$SourceWorkloadNamespace$\"}[2m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "CPU request allocation",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{container=~\"^$Container$\", namespace=~\"^$Namespace$\"}) / sum(count(node_cpu_seconds_total{mode='system'}) by (cpu)) \n"
    }
   ]
  },
  {
   "title": "Pods resources",
   "type": "table",
   "gridPos": { "h": 20, "w": 20, "x": 4, "y": 16 },
   "targets": [
    {
     "expr": "count(kube_pod_container_info{container=~\"^$Container$\", namespace=~\"^$Namespace$\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{container=~\"^$Container$\", namespace=~\"^$Namespace$\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{container=~\"^$Container$\", namespace=~\"^$Namespace$\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{container=~\"^$Container$\", namespace=~\"^$Namespace$\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{container=~\"^$Container$\", namespace=~\"^$Namespace$\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=~\"^$Container$\",namespace=~\"^$Namespace$\", container!~\"POD\"}[5m])) by (pod)\n/ sum(kube_pod_container_resource_limits_cpu_cores{container=~\"^$Container$\", namespace=~\"^$Namespace$\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{container=~\"^$Container$\",namespace=~\"^$Namespace$\",container!=\"\", container!~\"POD\"}) by (pod)\n/ sum(kube_pod_container_resource_limits_memory_bytes{container=~\"^$Container$\", namespace=~\"^$Namespace$\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "sum(kube_pod_container_status_last_terminated_reason{container=~\"^$Container$\", namespace=~\"^$Namespace$\", reason!=\"Completed\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "sum(kube_pod_container_status_restarts_total{container=~\"^$Container$\", namespace=~\"^$Namespace$\", reason!=\"Completed\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "CPU limit allocation",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{container=~\"^$Container$\", namespace=~\"^$Namespace$\"}) / sum(count(node_cpu_seconds_total{mode='system'}) by (cpu)) \n"
    }
   ]
  },
  {
   "title": "Memory request allocation",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{container=~\"^$Container$\", namespace=~\"^$Namespace$\"}) / sum(node_memory_MemTotal_bytes{})"
    }
   ]
  },
  {
   "title": "Memory limit allocation",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{container=~\"^$Container$\", namespace=~\"^$Namespace$\"}) / sum(node_memory_MemTotal_bytes{})\n\n"
    }
   ]
  },
  {
   "title": "Pods CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n    rate(container_cpu_usage_seconds_total{container=~\"^$Container$\",namespace=~\"^$Namespace$\", container!~\"POD\"}[5m]))\nby (container)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Pods CPU throttled usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n    rate(container_cpu_cfs_throttled_seconds_total{container=~\"^$Container$\",namespace=~\"^$Namespace$\", container!~\"POD\"}[5m]))\nby (container)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Pod Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container=~\"^$Container$\",namespace=~\"^$Namespace$\",container!=\"\", container!~\"POD\"}) by (container)  ",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 19, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\n  node_memory_MemTotal_bytes{kubernetes_node=~\"^$Node$\"}\n- node_memory_MemFree_bytes{kubernetes_node=~\"^$Node$\"}\n- node_memory_Buffers_bytes{kubernetes_node=~\"^$Node$\"}\n- node_memory_Cached_bytes{kubernetes_node=~\"^$Node$\"}\n) / sum(node_memory_MemTotal_bytes{kubernetes_node=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Node Memory usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 53 },
   "targets": [
    {
     "expr": "sum(\n  node_memory_MemTotal_bytes{kubernetes_node=~\"^$Node$\"}\n- node_memory_MemFree_bytes{kubernetes_node=~\"^$Node$\"}\n- node_memory_Buffers_bytes{kubernetes_node=~\"^$Node$\"}\n- node_memory_Cached_bytes{kubernetes_node=~\"^$Node$\"}\n) / sum(node_memory_MemTotal_bytes{kubernetes_node=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Cpu usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 19, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(node_load1{kubernetes_node=~\"^$Node$\"})\n"
    }
   ]
  },
  {
   "title": "Node CPU usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 58 },
   "targets": [
    {
     "expr": "sum(node_load1{kubernetes_node=~\"^$Node$\"})\n"
    }
   ]
  },
  {
   "title": "Node filesystem usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 19, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "( sum(node_filesystem_size_bytes{mountpoint=\"/\", kubernetes_node=~\"^$Node$\"}) \n- sum(node_filesystem_free_bytes{mountpoint=\"/\", kubernetes_node=~\"^$Node$\"}) ) \n/ sum(node_filesystem_size_bytes{mountpoint=\"/\", kubernetes_node=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Node filesystem usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 63 },
   "targets": [
    {
     "expr": "( sum(node_filesystem_size_bytes{mountpoint=\"/\", kubernetes_node=~\"^$Node$\"}) \n- sum(node_filesystem_free_bytes{mountpoint=\"/\", kubernetes_node=~\"^$Node$\"}) ) \n/ sum(node_filesystem_size_bytes{mountpoint=\"/\", kubernetes_node=~\"^$Node$\"})"
    }
   ]
  }
 ]
}
{
 "title": "Vote App Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Frontend P50",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(istio_request_duration_seconds_bucket{reporter=\"destination\", destination_workload_namespace=\"vote-app-dev\", destination_workload=~\"frontend.*\"}[1m])) by (le))"
    }
   ]
  },
  {
   "title": "Frontend P90",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(istio_request_duration_seconds_bucket{reporter=\"destination\", destination_workload_namespace=\"vote-app-dev\", destination_workload=~\"frontend.*\"}[1m])) by (le))"
    }
   ]
  },
  {
   "title": "Frontend success rate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"destination\", destination_workload_namespace=\"vote-app-dev\", destination_workload=~\"frontend.*\", response_code!~\"5.*\"}[1m])) / sum(irate(istio_requests_total{reporter=\"destination\", destination_workload_namespace=\"vote-app-dev\", destination_workload=~\"frontend.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "Backend P50",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(istio_request_duration_seconds_bucket{reporter=\"destination\", destination_workload_namespace=\"vote-app-dev\", destination_workload=~\"backend.*\"}[1m])) by (le))"
    }
   ]
  },
  {
   "title": "Backend P90",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(istio_request_duration_seconds_bucket{reporter=\"destination\", destination_workload_namespace=\"vote-app-dev\", destination_workload=~\"backend.*\"}[1m])) by (le))"
    }
   ]
  },
  {
   "title": "Backend success rate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"destination\", destination_workload_namespace=\"vote-app-dev\", destination_workload=~\"backend.*\", response_code!~\"5.*\"}[1m])) / sum(irate(istio_requests_total{reporter=\"destination\", destination_workload_namespace=\"vote-app-dev\", destination_workload=~\"backend.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "Frontend",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"destination\", destination_workload_namespace=\"vote-app-dev\",source_app=\"istio-ingressgateway\", destination_workload=~\"frontend.*\", response_code=\"200\"}[1m]))"
    }
   ]
  },
  {
   "title": "Frontend running containers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(irate(container_last_seen{namespace=\"vote-app-dev\", container=\"frontend\"}[1m]))"
    }
   ]
  },
  {
   "title": "Backend",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 12, "y": 4 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"destination\", destination_workload_namespace=\"vote-app-dev\", source_app=~\"frontend.*\", destination_workload=~\"backend.*\", response_code=\"200\"}[1m]))"
    }
   ]
  },
  {
   "title": "Backend running containers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(irate(container_last_seen{namespace=\"vote-app-dev\", container=\"backend\"}[1m]))"
    }
   ]
  },
  {
   "title": "Frontend memory usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container_name=\"frontend\"}) by (pod_name)\n/ \nsum(label_join(kube_pod_container_resource_limits_memory_bytes{container=\"frontend\"}, \"pod_name\", \"\", \"pod\")) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Frontend cpu usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 8 },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container_name=\"frontend\"}[1m])) by (pod_name)\n/ \nsum(label_join(kube_pod_container_resource_limits_cpu_cores{container=\"frontend\"}, \"pod_name\", \"\", \"pod\")) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Frontend memory usage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container_name=\"frontend\"})\n/ \nsum(label_join(kube_pod_container_resource_limits_memory_bytes{container=\"frontend\"}, \"pod_name\", \"\", \"pod\"))"
    }
   ]
  },
  {
   "title": "Backend memory usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container_name=\"backend\"}) by (pod_name)\n/ \nsum(label_join(kube_pod_container_resource_limits_memory_bytes{container=\"backend\"}, \"pod_name\", \"\", \"pod\")) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Backend cpu usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 8 },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container_name=\"backend\"}[1m])) by (pod_name)\n/ \nsum(label_join(kube_pod_container_resource_limits_cpu_cores{container=\"backend\"}, \"pod_name\", \"\", \"pod\")) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Backend memory usage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container_name=\"backend\"})\n/ \nsum(label_join(kube_pod_container_resource_limits_memory_bytes{container=\"backend\"}, \"pod_name\", \"\", \"pod\"))"
    }
   ]
  },
  {
   "title": "Frontend Cpu & Throttled",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container_name=\"frontend\"}[1m]))"
    },
    {
     "expr": "sum(irate(container_cpu_cfs_throttled_seconds_total{container_name=\"frontend\"}[1m])) "
    }
   ]
  },
  {
   "title": "Backend Cpu & Throttled",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container_name=\"backend\"}[1m]))"
    },
    {
     "expr": "sum(irate(container_cpu_cfs_throttled_seconds_total{container_name=\"backend\"}[1m])) "
    }
   ]
  },
  {
   "title": "Redis Cpu & Throttled",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container_name=\"redis\"}[1m]))"
    },
    {
     "expr": "sum(irate(container_cpu_cfs_throttled_seconds_total{container_name=\"redis\"}[1m])) "
    }
   ]
  },
  {
   "title": "Redis memory usage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container_name=\"redis\"}) by (pod_name) "
    }
   ]
  },
  {
   "title": "Redis cpu usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 16 },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container_name=\"redis\"}[1m])) by (pod_name)\n/ \nsum(label_join(kube_pod_container_resource_limits_cpu_cores{container=\"redis\"}, \"pod_name\", \"\", \"pod\")) by (pod_name)"
    }
   ]
  }
 ]
}
{
 "title": "Istio Canary",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "query_result(sum(istio_requests_total) by (destination_workload_namespace) or sum(istio_tcp_sent_bytes_total) by (destination_workload_namespace))"
   },
   {
    "name": "primary",
    "label": "Primary",
    "query": "query_result(sum(istio_requests_total{destination_workload_namespace=~\"$namespace\"}) by (destination_workload))"
   },
   {
    "name": "canary",
    "label": "Canary",
    "query": "query_result(sum(istio_requests_total{destination_workload_namespace=~\"$namespace\"}) by (destination_workload))"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "<div class=\"dashboard-header text-center\">\n<span>RED: $canary.$namespace</span>\n</div>"
  },
  {
   "title": "Primary: Incoming Request Volume",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 3 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "round(sum(rate(istio_requests_total{reporter=\"destination\",destination_workload_namespace=~\"$namespace\",destination_workload=~\"$primary\"}[30s])), 0.001)"
    }
   ]
  },
  {
   "title": "Incoming Success Rate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 3 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"destination\",destination_workload_namespace=~\"$namespace\",destination_workload=~\"$primary\",response_code!~\"5.*\"}[30s])) / sum(irate(istio_requests_total{reporter=\"destination\",destination_workload_namespace=~\"$namespace\",destination_workload=~\"$primary\"}[30s]))"
    }
   ]
  },
  {
   "title": "Canary: Incoming Request Volume",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 3 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "round(sum(rate(istio_requests_total{reporter=\"destination\",destination_workload_namespace=~\"$namespace\",destination_workload=~\"$canary\"}[30s])), 0.001)"
    }
   ]
  },
  {
   "title": "Incoming Success Rate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 3 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"destination\",destination_workload_namespace=~\"$namespace\",destination_workload=~\"$canary\",response_code!~\"5.*\"}[30s])) / sum(irate(istio_requests_total{reporter=\"destination\",destination_workload_namespace=~\"$namespace\",destination_workload=~\"$canary\"}[30s]))"
    }
   ]
  },
  {
   "title": "Primary: Request Duration",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\",destination_workload=~\"$primary\", destination_workload_namespace=~\"$namespace\"}[1m])) by (le))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\",destination_workload=~\"$primary\", destination_workload_namespace=~\"$namespace\"}[1m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\",destination_workload=~\"$primary\", destination_workload_namespace=~\"$namespace\"}[1m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Canary: Request Duration",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\",destination_workload=~\"$canary\", destination_workload_namespace=~\"$namespace\"}[1m])) by (le))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\",destination_workload=~\"$canary\", destination_workload_namespace=~\"$namespace\"}[1m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(istio_request_duration_seconds_bucket{reporter=\"destination\",destination_workload=~\"$canary\", destination_workload_namespace=~\"$namespace\"}[1m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 11 },
   "content": "<div class=\"dashboard-header text-center\">\n<span>USE: $canary.$namespace</span>\n</div>"
  },
  {
   "title": "Primary: CPU Usage by Pod",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s", "label": "CPU seconds / second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cpu=\"total\",namespace=\"$namespace\",pod_name=~\"$primary.*\", container_name!~\"POD|istio-proxy\"}[1m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Canary: CPU Usage by Pod",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "s", "label": "CPU seconds / second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cpu=\"total\",namespace=\"$namespace\",pod_name=~\"$canary.*\", pod_name!~\"$primary.*\", container_name!~\"POD|istio-proxy\"}[1m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Primary: Memory Usage by Pod",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",pod_name=~\"$primary.*\", container_name!~\"POD|istio-proxy\"}) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Canary: Memory Usage by Pod",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",pod_name=~\"$canary.*\", pod_name!~\"$primary.*\", container_name!~\"POD|istio-proxy\"}) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Primary: Network I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate (container_network_receive_bytes_total{namespace=\"$namespace\",pod_name=~\"$primary.*\"}[1m])) ",
     "legendFormat": "received"
    },
    {
     "expr": "-sum (rate (container_network_transmit_bytes_total{namespace=\"$namespace\",pod_name=~\"$primary.*\"}[1m]))",
     "legendFormat": "transmited"
    }
   ]
  },
  {
   "title": "Canary: Network I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate (container_network_receive_bytes_total{namespace=\"$namespace\",pod_name=~\"$canary.*\",pod_name!~\"$primary.*\"}[1m])) ",
     "legendFormat": "received"
    },
    {
     "expr": "-sum (rate (container_network_transmit_bytes_total{namespace=\"$namespace\",pod_name=~\"$canary.*\",pod_name!~\"$primary.*\"}[1m]))",
     "legendFormat": "transmited"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 32 },
   "content": "<div class=\"dashboard-header text-center\">\n<span>IN/OUTBOUND: $canary.$namespace</span>\n</div>"
  },
  {
   "title": "Primary: Incoming Requests by Source And Response Code",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(istio_requests_total{connection_security_policy=\"mutual_tls\", destination_workload_namespace=~\"$namespace\", destination_workload=~\"$primary\", reporter=\"destination\"}[30s])) by (source_workload, source_workload_namespace, response_code), 0.001)",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace }} : {{ response_code }} (🔐mTLS)"
    },
    {
     "expr": "round(sum(irate(istio_requests_total{connection_security_policy!=\"mutual_tls\", destination_workload_namespace=~\"$namespace\", destination_workload=~\"$primary\", reporter=\"destination\"}[30s])) by (source_workload, source_workload_namespace, response_code), 0.001)",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace }} : {{ response_code }}"
    }
   ]
  },
  {
   "title": "Canary: Incoming Requests by Source And Response Code",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(istio_requests_total{connection_security_policy=\"mutual_tls\", destination_workload_namespace=~\"$namespace\", destination_workload=~\"$canary\", reporter=\"destination\"}[30s])) by (source_workload, source_workload_namespace, response_code), 0.001)",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace }} : {{ response_code }} (🔐mTLS)"
    },
    {
     "expr": "round(sum(irate(istio_requests_total{connection_security_policy!=\"mutual_tls\", destination_workload_namespace=~\"$namespace\", destination_workload=~\"$canary\", reporter=\"destination\"}[30s])) by (source_workload, source_workload_namespace, response_code), 0.001)",
     "legendFormat": "{{ source_workload }}.{{ source_workload_namespace }} : {{ response_code }}"
    }
   ]
  },
  {
   "title": "Primary: Outgoing Requests by Destination And Response Code",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(istio_requests_total{connection_security_policy=\"mutual_tls\", source_workload_namespace=~\"$namespace\", source_workload=~\"$primary\", reporter=\"source\"}[30s])) by (destination_service, response_code), 0.001)",
     "legendFormat": "{{ destination_service }} : {{ response_code }} (🔐mTLS)"
    },
    {
     "expr": "round(sum(irate(istio_requests_total{connection_security_policy!=\"mutual_tls\", source_workload_namespace=~\"$namespace\", source_workload=~\"$primary\", reporter=\"source\"}[30s])) by (destination_service, response_code), 0.001)",
     "legendFormat": "{{ destination_service }} : {{ response_code }}"
    }
   ]
  },
  {
   "title": "Canary: Outgoing Requests by Destination And Response Code",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(istio_requests_total{connection_security_policy=\"mutual_tls\", source_workload_namespace=~\"$namespace\", source_workload=~\"$canary\", reporter=\"source\"}[30s])) by (destination_service, response_code), 0.001)",
     "legendFormat": "{{ destination_service }} : {{ response_code }} (🔐mTLS)"
    },
    {
     "expr": "round(sum(irate(istio_requests_total{connection_security_policy!=\"mutual_tls\", source_workload_namespace=~\"$namespace\", source_workload=~\"$canary\", reporter=\"source\"}[30s])) by (destination_service, response_code), 0.001)",
     "legendFormat": "{{ destination_service }} : {{ response_code }}"
    }
   ]
  }
 ]
}