server:
  global:
    scrape_interval: 10s
extraScrapeConfigs: |
  - job_name: 'istio-mesh'
    kubernetes_sd_configs:
    - role: endpoints
      namespaces:
        names:
        - istio-system

    relabel_configs:
    - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
      action: keep
      regex: istio-telemetry;prometheus

  # Scrape config for envoy stats
  - job_name: 'envoy-stats'
    metrics_path: /stats/prometheus
    kubernetes_sd_configs:
    - role: pod

    relabel_configs:
    - source_labels: [__meta_kubernetes_pod_container_port_name]
      action: keep
      regex: '.*-envoy-prom'
    - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
      action: replace
      regex: ([^:]+)(?::\d+)?;(\d+)
      replacement: $1:15090
      target_label: __address__
    - action: labelmap
      regex: __meta_kubernetes_pod_label_(.+)
    - source_labels: [__meta_kubernetes_namespace]
      action: replace
      target_label: namespace
    - source_labels: [__meta_kubernetes_pod_name]
      action: replace
      target_label: pod_name

  - job_name: 'istio-policy'
    kubernetes_sd_configs:
    - role: endpoints
      namespaces:
        names:
        - istio-system


    relabel_configs:
    - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
      action: keep
      regex: istio-policy;http-monitoring

  - job_name: 'istio-telemetry'
    kubernetes_sd_configs:
    - role: endpoints
      namespaces:
        names:
        - istio-system

    relabel_configs:
    - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
      action: keep
      regex: istio-telemetry;http-monitoring

  - job_name: 'pilot'
    kubernetes_sd_configs:
    - role: endpoints
      namespaces:
        names:
        - istio-system

    relabel_configs:
    - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
      action: keep
      regex: istio-pilot;http-monitoring

  - job_name: 'galley'
    kubernetes_sd_configs:
    - role: endpoints
      namespaces:
        names:
        - istio-system

    relabel_configs:
    - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
      action: keep
      regex: istio-galley;http-monitoring

  - job_name: 'citadel'
    kubernetes_sd_configs:
    - role: endpoints
      namespaces:
        names:
        - istio-system

    relabel_configs:
    - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
      action: keep
      regex: istio-citadel;http-monitoring