"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 3.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import structlog
from elasticapm.handlers.structlog import structlog_processor

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ta+1z4uwk9$4v1=##m_lu9avcj5c#6q6m3^gyjn^^*9c-_)oc0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

# Application definition

INSTALLED_APPS = [
    'vote.apps.VoteConfig',
    'status.apps.StatusConfig',
    # 'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    # 'django.contrib.sessions',
    # 'django.contrib.messages',
    'elasticapm.contrib.django',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    # 'django.middleware.security.SecurityMiddleware',
    # 'django.contrib.sessions.middleware.SessionMiddleware',
    # 'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    # 'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'django.contrib.messages.middleware.MessageMiddleware',
    # 'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'django_structlog.middlewares.RequestMiddleware',
    'elasticapm.contrib.django.middleware.TracingMiddleware',
    'elasticapm.contrib.django.middleware.Catch404Middleware',
]

ROOT_URLCONF = 'app.urls'

SETTINGS_PATH = os.path.dirname(os.path.dirname(__file__))

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(SETTINGS_PATH, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "json": {
            "()": structlog.stdlib.ProcessorFormatter,
            "processor": structlog.processors.JSONRenderer(),
        },
        "console": {
            "()": structlog.stdlib.ProcessorFormatter,
            "processor": structlog.dev.ConsoleRenderer(),
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "json",
        },
        "elasticapm": {
            "class": "elasticapm.contrib.django.handlers.LoggingHandler",
            "level": os.getenv("DJANGO_ELASTICAPM_LOG_LEVEL", "INFO"),
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "elasticapm"],
            "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
        },
        "django.server": {
            "handlers": ["console", "elasticapm"],
            "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
        },
        "django.request": {
            "handlers": ["console", "elasticapm"],
            "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
        },
        "vote": {
            "handlers": ["console", "elasticapm"],
            "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
        },
        "elasticapm": {
            "handlers": ["console"],
            "level": os.getenv("DJANGO_ELASTICAPM_LOG_LEVEL", "INFO"),
        },
    },
}

# structlog.configure(
#     processors=[
#         # structlog.stdlib.filter_by_level,
#         # structlog.processors.TimeStamper(fmt="iso"),
#         # structlog.stdlib.add_logger_name,
#         # structlog.stdlib.add_log_level,
#         # structlog.stdlib.PositionalArgumentsFormatter(),
#         # structlog.processors.StackInfoRenderer(),
#         # structlog.processors.format_exc_info,
#         # structlog.processors.UnicodeDecoder(),
#         # structlog.processors.ExceptionPrettyPrinter(),
#         # structlog.stdlib.ProcessorFormatter.wrap_for_formatter,
#         structlog_processor,
#     ],
#     # context_class=structlog.threadlocal.wrap_dict(dict),
#     # logger_factory=structlog.stdlib.LoggerFactory(),
#     # wrapper_class=structlog.stdlib.BoundLogger,
#     cache_logger_on_first_use=True,
# )

structlog_processors = [
        structlog.stdlib.filter_by_level,
        structlog.processors.TimeStamper(fmt="iso", key="@timestamp"),
        structlog.stdlib.add_logger_name,
        structlog.stdlib.add_log_level,
        structlog.stdlib.PositionalArgumentsFormatter(),
        structlog.processors.StackInfoRenderer(),
        structlog.processors.format_exc_info,
        structlog.processors.UnicodeDecoder(),
        structlog.processors.ExceptionPrettyPrinter(),
        structlog.stdlib.ProcessorFormatter.wrap_for_formatter,
    ]

try:
    from elasticapm.handlers.structlog import structlog_processor
    structlog_processors.insert(4, structlog_processor)
except ImportError:
    pass


structlog.configure(
    processors=structlog_processors,
    context_class=structlog.threadlocal.wrap_dict(dict),
    logger_factory=structlog.stdlib.LoggerFactory(),
    wrapper_class=structlog.stdlib.BoundLogger,
    cache_logger_on_first_use=True,
)

VOTE1VALUE = os.getenv("VOTE1VALUE", "Cats")
VOTE2VALUE = os.getenv("VOTE2VALUE", "Dogs")
TITLE = os.getenv("TITLE", "Azure Voting App")
FRONTEND_VERSION = os.getenv("FRONTEND_VERSION", "local")
BACKEND_BASE_URL = os.getenv("BACKEND_BASE_URL", "http://localhost:8081/api/hits")
