apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ template "name" . }}
    version: "{{ .Values.service.version }}"
spec:
  ports:
  - name: redis-backend
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  selector:
    app: {{ template "name" . }}
